<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
<%
' xxxxxxxxxxxxxxxxxxxxxxx DO NOT EDIT THIS FILE xxxxxxxxxxxxxxxxxxxxxxxx
Response.Expires = 0
Response.AddHeader "Cache-Control", "no-store"
g_filename = "Login.asp"

' DetectionDOSFix - Flags that session params required for validation are not loaded.
is_validate_params_not_required = true
Session("CheckLang") = True
%>
<!--#include virtual="InternalSite/inc/strings.inc"-->
<!--#include virtual="InternalSite/inc/Login.inc"-->
<!--#include virtual="InternalSite/inc/customDefault.inc"-->
<!--#include virtual="InternalSite/inc/agentDetection.inc"-->
<%

'----------------------------------------------------------------
'Redirect to Mobile Browsing InternalSite if it's a feature phone
'----------------------------------------------------------------
if isFeaturePhone then
        HEAVY_TRACE("Client identified as feature phone. Redirecting to MobileBrowsing feature.")
		Response.Redirect("/InternalSite/M/default.aspx?site_name="&g_site_name&"&secure="&g_secure&"&resource_id="&g_resource_id&"&login_type="&g_login_type&"&orig_url="&g_orig_url)
		Response.End()
end if
'----------------------------------------------------------------

'DetectionDOSFix - Store include file names in Application and not in Session.
include Application(g_site_name&g_secure&LOGIN_INC)

userNameStr = GetString(105, "User name:")
passwordStr = GetString(106, "Password:")
repositoryStr = GetString(107, "Authenticate using:")

loginTitle = GetString(829, "Microsoft Forefront Unified Access Gateway - Logon Page")

'Variables are global since they are in use later on this page
dim agent, lowerAgent, bIE6onXPSP2, bIE6onWin2003, bIE6onWinVista, bIEonWin7, Components_ProblematicXPSP2, bSiteAllowsPopups, bUsePortalFrame, bWin64, sDisabled, bShowPopupMsg

sDisabled = ""
if isPDA = true then
    sDisabled = "disabled"
end if

function isDisplayMsg
	dim retValue
	retValue = false

	if g_login_type = RESOURCE_OPERATION_LOGIN then
		'getting params only when necessary
		agent = Request.ServerVariables("HTTP_USER_AGENT")
		lowerAgent = LCase(agent)
		bIE6onXPSP2 = false
		bIE6onWin2003 = false
		bIE6onWinVista = false
		bIEonWin7 = false
		if InStr(lowerAgent,"sv1") > 0 or InStr(lowerAgent,"msie 7") > 0 or InStr(lowerAgent,"msie 8") > 0 then 'Popup blocker
			if InStr(lowerAgent,"windows nt 5.1") > 0 then 'Win XP
				bIE6onXPSP2 = true
			elseif InStr(lowerAgent,"windows nt 5.2") > 0 then 'Win 2003
				bIE6onWin2003 = true
			elseif InStr(lowerAgent,"windows nt 6.0") > 0 then 'Win Vista / Win Server 2008
				bIE6onWinVista = true
			elseif InStr(lowerAgent,"windows nt 6.1") > 0 then 'Win 7
				bIEonWin7 = true
			end if
		end if

		if bIE6onXPSP2 or bIE6onWin2003 or bIE6onWinVista or InStr(lowerAgent,"msie 7") > 0 or InStr(lowerAgent,"msie 8") > 0 then
			'UsePortalFrame is true when admin mark this option on configuration. This is the default behavior,
			'and in this case when using the portal, popup blocker does not block the div timout notifications.
			bUsePortalFrame = GetSessionParam(g_cookie,"UsePortalFrame")
			if EvaluateSessionParam(bUsePortalFrame) = false then
				'SiteIn_PopupBlocker_AllowedList is set to true by detection when user chooses to add site to popup blocker allow list
				bSiteAllowsPopups = GetSessionParam(g_cookie,"SiteIn_PopupBlocker_AllowedList")
				if EvaluateSessionParam(bSiteAllowsPopups) <> true then
					retValue = true
				end if
			end if
			if bIE6onXPSP2 then
				Components_ProblematicXPSP2 = GetSessionParam(g_cookie,"Components_ProblematicXPSP2")
				if EvaluateSessionParam(Components_ProblematicXPSP2) = true then
					retValue = true
					bShowPopupMsg = true
				end if
			end if
		end if

		'checking useragent for 64-bit browser
		bWin64 = false
		if ParameterAsBool("Win64") then
			bWin64 = true
			retValue = true
		end if
	end if
	isDisplayMsg = retValue
end function
%>
<HTML>
<HEAD>
<noscript>
<meta http-equiv=refresh content="0;url=<%Response.Write(GetSiteErrorPage() & "?error_code=115")%>">
<span style="position:relative; height:120%;">
<h3><%=GetString(85, "The site cannot be accessed")%></h3>
<%=GetString(86, "To access this site, adjust the security settings in the browser to a lower level.")%><br>
<a href='<%Response.Write( GetSiteErrorPage() & "?error_code=123")%>'><%= GetString(87, "Click here")%></a>&nbsp;
<%=GetString(88, "for more information.")%>
</span>
</noscript>
<META HTTP-EQUIV="Cache-Control" CONTENT="no-cache">
<META HTTP-EQUIV="Expires" CONTENT="-1">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
<TITLE><%=loginTitle%></TITLE>
<LINK rel="STYLESHEET" type="text/css" href="<%=Application(g_site_name&g_secure&TEMPLATE_CSS)%>">
<%
rds_effective = InStr(LCase(Request.ServerVariables("HTTP_USER_AGENT")),"msie") and Session("SiteInfo").UseRdsSso
if ExistOnServer("/InternalSite/scripts/CustomUpdate/" &  g_site_name & g_secure & "rds-sso-privileged.js") then
    rds_effective = rds_effective and GetSessionParam(g_cookie,"IsSessionPrivilege")
end if
if rds_effective then
    rds_js_file ="/InternalSite/scripts/CustomUpdate/" &  g_site_name & g_secure & "rds.js"
    if not ExistOnServer(rds_js_file) then
        rds_js_file ="/InternalSite/scripts/CustomUpdate/rds.js"
        if not ExistOnServer(rds_js_file) then
            rds_js_file ="/InternalSite/scripts/rds.js"
        end if
    end if%>
<script language="JavaScript" src="<%=rds_js_file%>"></script>
<script language="JavaScript" src="/InternalSite/scripts/rdsbase.js"></script>
<%end if%>
<script language="JavaScript">
var loginDone = false;

var timeoutURL = "";
var bHandleSessionTimeout = false;

<%if g_login_type = RESOURCE_OPERATION_LOGIN_AFTER_LOGOFF then%>
	//WhlScheduledLogoff cookie is used in Web Monitor to prevent calls on scheduled logoff status
	document.cookie = "WhlScheduledLogoff=True; path=/;";
	try
	{
		window.top.document.title = "<%=loginTitle%>";
		parent.document.getElementById("portal_frameset").rows = "100%, 0px";
	}
	catch(e)
	{}

	var today = new Date();
	var expiredDate = new Date(today.getTime() + 60*60*1000);
	var expiredDateGMT = expiredDate.toGMTString();
	//set value of WhlLogoffReason
	document.cookie = "WhlLogoffReason=SCHEDULED_LOGOFF; expires=" + expiredDateGMT + ";path=/";

	bHandleSessionTimeout = true;
	timeoutURL = "<%=GetSiteLogoffPage()%>?site_name=<%=g_site_name%>&secure=<%=g_secure%>";
<%elseif g_login_type = RESOURCE_OPERATION_LOGIN then%>
	try
	{
		if (parent.parent.document.getElementById("portal_frameset"))
			parent.location.replace("<%=GetSiteLogoffPage()%>?site_name=<%=g_site_name%>&secure=<%=g_secure%>");
	}
	catch(e)
	{}

	bHandleSessionTimeout = true;
	timeoutURL = "<%=GetSiteErrorPage()%>" + "?error_code=117";
<%end if%>

//for old browsers. To support document.getElementById
if(document.all && !document.getElementById)
{
	document.getElementById = function(id)
	{
		return document.all[id];
	}
}

function SubmitForm()
{
	if (loginDone)
		return false;
	for (i = 0 ; i < document.form1.length ; i++)
	{
		var tempobj = document.form1.elements[i];
		if (tempobj.type == 'text' || tempobj.type == 'password')
		{
			if (tempobj.value.toString() == "")
			{
				alert("<%=GetString(102, "Complete all the required fields before logging on.")%>");
				SetFocus();
				return false;
			}
		}
	}
<%if rds_effective then%>
	if (!rds_sso_in_hook("<%=Server.HTMLEncode(Session("SiteInfo").PublicName)%>","<%=Server.HTMLEncode(Session("SiteInfo").CertHash)%>"))
		return false;
<%end if%>
	loginDone = true;
	return true;
}

function ResetForm()
{
	document.form1.reset();
	SetFocus();
	return false;
}

function SetFocus()
{
	if (document.form1.elements[0].value.toString() == "")
		document.form1.elements[0].focus();
	else if (document.form1.elements[1].value.toString() == "")
		document.form1.elements[1].focus();
	else
		document.form1.elements[2].focus();
}

var BlackShieldGrIDPageLocation = 'http://IP Address or hostname of BlackShield ID Server/blackshieldss/index.aspx';


function loadGrID()
{
	if (document.form1.useGrID.checked == 1) {
		otpOutter.style.display="";
		document.getElementById('otp').src = BlackShieldGrIDPageLocation + '?getChallengeImage=true&userName=' +  document.form1.user_name.value.toString();
   	} else {
		otpOutter.style.display="none";
		document.getElementById('otp').src = "";
	}
}

function selectLang()
{
	var today = new Date();
	//remove host cookie in case it exists
	var oldExpiredDate = new Date(today.getTime() - 365 * 24 * 60 * 60 * 1000); // -1 year
	var oldExpiredDateGMT = oldExpiredDate.toGMTString();
	var oldCookie = "WhlLanguage=NA; expires=" + oldExpiredDateGMT + ";path=/;";
	
	<%if g_trunk_domain_name <> GetRealDomain then%>
		//domain without AAM, or shortname/IP - remove domain cookie%>
		oldCookie = oldCookie + " domain=.<%=GetRealDomain()%>";
	<%end if%>

	document.cookie = oldCookie;
	//set new cookie
	var expiredDate = new Date(today.getTime() + 365 * 24 * 60 * 60 * 1000); // +1 year
	var expiredDateGMT = expiredDate.toGMTString();
	document.cookie = "WhlLanguage=" + document.form1.language.value + "; expires=" + expiredDateGMT + ";path=/;<%=GetCookieDomainAttr()%>";	

    	// We need to reload the login page here, but only if the user hasn't already entered a username and/or password.
    	var confirmChangeLang = true;
    	for (i = 0 ; i < document.form1.length ; i++)
	{
		var tempobj=document.form1.elements[i];
		if (tempobj.type=='text' || tempobj.type=='password')
		{
			if (tempobj.value.toString() != "")
			{
				confirmChangeLang = confirm("<%=GetString(113, "Do you want to reload the page in the selected language?\nAll data entered on the page will be deleted.")%>");
				break;
			}
		}
	}
    	if (confirmChangeLang)
		self.location.replace("/InternalSite/RedirectToOrigURL.asp?abandon=0&site_name=<%=g_site_name%>&secure=<%=g_secure%>");
}

function window_onload()
{
        <%if rds_effective then%>
        rds_sso_init();
        <%end if%>
	if(document.body)
		document.body.style.overflow = "";
	SetFocus();
	<%if g_login_type = RESOURCE_OPERATION_LOGIN or g_login_type = RESOURCE_OPERATION_LOGIN_AFTER_LOGOFF then%>
	getWhlCookie();
	<%end if%>
	<%if isRSASoftToken = true then%>
	createRSASoftTokenLinks();
	<%end if%>
}

function keyDetect(e)
{
	if(!e)
		e = window.event;
	if(!e)
	{
		return;
	}
	var theKey = e.which ? e.which : (e.keyCode ? e.keyCode : (e.charCode ? e.charCode : 0));
	var agt = navigator.userAgent.toLowerCase();
	if (theKey == 13 || theKey == 3)
	{
		if(SubmitForm())
			document.form1.submit();
	}
}

var capsLockNote = "<%=GetString(111, "Note: The Caps Lock key is on. Passwords are case-sensitive.")%>";
</script>
<script language="JavaScript" src="/InternalSite/scripts/capsLock.js"></script>
<%if g_login_type = RESOURCE_OPERATION_LOGIN or g_login_type = RESOURCE_OPERATION_LOGIN_AFTER_LOGOFF then%>
<script language="JavaScript" src="/InternalSite/scripts/loginTimeout.js"></script>
<%end if%>
<%if isRSASoftToken = true then%>
<script language="JavaScript" src="/InternalSite/scripts/RSASoftToken.js"></script>
<%end if%>
</HEAD>
<BODY height="100%" onload="window_onload();" style="overflow:hidden;">
<table height="100%" id="loginMainTable" width="100%" cellspacing="0" cellpadding="0">
	<tr>
		<td>
			<TABLE align="center" class="blueBorder" cellspacing="0" cellpadding="0">
				<!--#include virtual="InternalSite/inc/logo.inc"-->
				<tr>
					<td valign="top" class="contentleft"></td>
					<td align="center" class="internalTD">
						<table width="100%" height="100%" cellspacing="0" cellpadding="0">
							<FORM id=form1 name=form1 autocomplete="off" method=post action="/InternalSite/Validate.asp" onsubmit="return(SubmitForm());">
							<tr>
								<td valign="top">
									<TABLE border=0 cellspacing="0" cellpadding="0" class="content">
										<%if error_msg <> "" then%>
										<tr>
											<td class="errormsg"><%=error_msg%></td>
										</tr>
										<%end if%>
										<%if g_login_type = RESOURCE_OPERATION_LOGIN_ON_THE_MOVE then %>
										<tr>
											<td class="regText"><%=GetString(103, "Enter additional credentials to access applications associated with the credentials from the portal page.")%></td>
										</tr>
										<%end if%>



										<tr>
											<td class="msgText"><%=GetString(104, "Log On")%></td>
										</tr>
									</TABLE>
									<TABLE border=0 cellspacing="0" cellpadding="0" class="content">
										<%
										if g_login_type = RESOURCE_OPERATION_LOGIN and GetSiteFixRepositories() then
											use_the_same_user_name = GetSiteUseTheSameUserName()
											if use_the_same_user_name then%>
											<TR>
												<TD class="paramText"><%=userNameStr%></TD>
												<TD><INPUT class="paramTextbox" TYPE="text" ID="user_name" NAME="user_name" maxLength="<%=UserNameLimit%>" size="11"></TD>
											</TR>
											<%end if
											for each repository_name in repositories.NameVec
												if not use_the_same_user_name then%>
												<TR>
													<TD class="paramText"><%=repository_name%>&nbsp;<%=GetString(108, "User name:")%></TD>
													<TD><INPUT class="paramTextbox" TYPE="text" ID="user_name" NAME="user_name" maxLength="<%=UserNameLimit%>" size="11" onchange="checkradio();"></TD>
												</TR>
												<%end if%>
											<TR>
												<TD class="paramText"><%=repository_name%>&nbsp;<%=GetString(109, "Password:")%></TD>
												<TD><INPUT class="paramTextbox" TYPE="password" ID="password" NAME="password" maxLength="<%=PasswordLimit%>" onkeypress="capsDetect(arguments[0]);" size="11"></TD>
											</TR>
											<%next
										elseif g_login_type = RESOURCE_OPERATION_LOGIN_AFTER_LOGOFF then
											dim logoff_repositories
											logoff_repositories = repositories.NameVec
											if UBound(GetSiteRepositoriesVec()) = 0 then
												dont_show_repository = true
											else
												dont_show_repository = false
											end if%>
											<TR>
												<TD class="paramText"><%=userNameStr%></TD>
												<TD>
													<INPUT class="paramTextboxReadonly" TYPE="text" ID="dummy_user_name" NAME="dummy_user_name" maxLength="<%=UserNameLimit%>" VALUE="<%=logoff_repositories(0)%>" readonly <%=sDisabled%> size="11">
													<INPUT class="paramTextboxReadonly" TYPE="hidden" ID="user_name" NAME="user_name" VALUE="<%=logoff_repositories(0)%>">
												</TD>
											</TR>
											<TR>
												<TD class="paramText"><%=passwordStr%></TD>
												<TD><INPUT class="paramTextbox" TYPE="password" ID="password" NAME="password" maxLength="<%=PasswordLimit%>" onkeypress="capsDetect(arguments[0]);" size="11"></TD>
											</TR>
											<%if dont_show_repository then%>
											<INPUT type="hidden" ID="repository" NAME="repository" VALUE="<%=logoff_repositories(1)%>">
											<%else%>
											<TR>
												<TD class="paramText"><%=repositoryStr%></TD>
												<TD>
													<INPUT class="paramTextboxReadonly" TYPE="text" ID="dummy_repository" NAME="dummy_repository" maxLength="30" VALUE="<%=logoff_repositories(1)%>" readonly <%=sDisabled%> size="11"></TD>
													<INPUT class="paramTextboxReadonly" TYPE="hidden" ID="repository" NAME="repository" VALUE="<%=logoff_repositories(1)%>">
												</TD>
											</TR>
											<%end if
										else ' if g_login_type <> RESOURCE_OPERATION_LOGIN or GetSiteFixRepositories() = false%>
											<TR>
												<TD class="paramText"><%=userNameStr%></TD>
												<TD><INPUT class="paramTextbox" TYPE="text" ID="user_name" NAME="user_name" maxLength="<%=UserNameLimit%>" size="11"></TD>
											</TR>
											<TR>
												<TD class="paramText"><%=passwordStr%></TD>
												<TD><INPUT class="paramTextbox" TYPE="password" ID="password" NAME="password" maxLength="<%=PasswordLimit%>" onkeypress="capsDetect(arguments[0]);" size="11"></TD>
											</TR>
											<%
											if UBound(repositories.NameVec) = 0 then
												dont_show_repository = true
											else
												dont_show_repository = false
											end if
											if dont_show_repository then
												dim login_repositories
												login_repositories = repositories.NameVec
												if g_login_type = RESOURCE_OPERATION_LOGIN_AUTHENTICATION or g_login_type = RESOURCE_OPERATION_LOGIN_AUTHORIZATION then%>
													<TR>
														<TD class="paramText"><%=repositoryStr%></TD>
														<TD>
															<INPUT class="paramTextboxReadonly" TYPE="text" ID="dummy_repository" NAME="dummy_repository" maxLength="30" VALUE="<%=login_repositories(0)%>" readonly <%=sDisabled%> size="11"></TD>
															<INPUT class="paramTextboxReadonly" TYPE="hidden" ID="repository" NAME="repository" VALUE="<%=login_repositories(0)%>">
														</TD>
													</TR>
												<%else%>
													<INPUT type="hidden" ID="repository" NAME="repository" VALUE="<%=login_repositories(0)%>" size="11">
												<%end if
											else
											%>
											<TR>
												<TD class="paramText"><%=repositoryStr%></TD>
												<TD>
												<%if g_login_type = RESOURCE_OPERATION_LOGIN and GetSiteShowRepositories() = false then%>
													<INPUT class="paramTextbox" TYPE="text" ID="repository" NAME="repository" maxLength="30" size="11">
												<%else%>
													<select class="paramTextbox" type="combbox" id="repository" name="repository" maxLength="35" onkeypress="keyDetect(event)">
													<% for each repository_name in repositories.NameVec %>
														<option value="<%=repository_name%>" <%if repository_name = repository then%>selected<%end if%>><%=repository_name%></option>
													<%next%>
													</select>
												<%end if%>
												</TD>
											</TR>
											<%end if 'if dont_show_repository
										end if 'if g_login_type = RESOURCE_OPERATION_LOGIN and GetSiteFixRepositories()
										set repositories = Nothing
										include Application(g_site_name&g_secure&LOGIN_FORM_INC)
										%>
										<%if g_login_type = RESOURCE_OPERATION_LOGIN and ViewMultiLanguage() = 1 then%>
											<%
											set languageNodes = GetLanguages()
											if not languageNodes is Nothing then
												if languageNodes.length > 1 then
												%>
												<TR>
													<TD class="paramText"><%=GetString(112, "Language:")%></TD>
													<TD>
														<select class="paramTextbox" ID="language" NAME="language" onchange="selectLang()" onkeypress="keyDetect(event)">
														<%For Each node In languageNodes
															value = node.getAttribute("id")
															if Session("lang") = value then
																Response.write("<option value=""" & value & """ selected>" & node.text & " (" & value & ")</option>")
															else
																Response.write("<option value=""" & value & """>" & node.text & " (" & value & ")</option>")
															end if
														Next%>
														</select>
													</TD>
												</TR>
												<%end if
												set languageNodes = Nothing
											end if
										end if%>
										<tr>
											<td class="paramText">Use GrIDsure:</td>
											<td><INPUT type="checkbox" name="useGrID" value="GrIDsure" onClick="loadGrID();"></td>
										</tr>
										<%if isPDA = false then%>
										<TR height="25px">
											<TD colspan="2" id="capsLockTD">&nbsp;</TD>
										</TR>
										<%end if%>
										<tr>
											<TD colspan="2" align="right">
												<input border="0" class="button" type="submit" id="submit_button" value="<%=GetString(62, "Log On")%>">
											</TD>
											<td></td>
										</tr>
									</TABLE>
								</td>
							</tr>
							<tr><td>
									<Table>

										<TR>
											<TD colspan="2"><div name="otpOutter" id="otpOutter" style="display:none;" ><img name="otp" id="otp" src="" frameborder="0" scrolling="no"/></div></TD>
										</TR>

									</Table>
							</td></tr>
							<input type="hidden" name ="site_name" id="site_name" value="<%=g_site_name%>">
							<input type="hidden" name ="secure" id="secure" value="<%=g_secure%>">
							<input type="hidden" name ="resource_id" id="resource_id" value="<%=g_resource_id%>">
							<input type="hidden" name ="login_type" id="login_type" value="<%=g_login_type%>">
                                                    <%if rds_effective then%>
							<input type="hidden" name ="rds_sso" id="rds_sso" value="">
                                                    <%end if%>

						    <%if isPDA = false and g_login_type = RESOURCE_OPERATION_LOGIN then%>
						    <tr>
						        <td>
						            <table cellspacing="0" cellpadding="0" class="content" width="100%">
						                <tr>
								            <td id="openerExistsTD" class="notification" style="display:none">
								            <%=GetString(110, "For security purposes, when you finish working with this site do one of the following:<li>Click the Logoff button to log off from the site.</li><li>Close all browser windows (including applications that are open in other windows).</li>")%>
								            </td>
							            </tr>
							            <!-- Windows XP Service Pack 2  / 2003 / Vista Message - Start -->
							            <%if isDisplayMsg() then%>
							            <tr>
								            <td class="notification">
								            <%if bIE6onXPSP2 then%>
									            <%=GetString(114, "You are accessing this site from an endpoint running Microsoft Windows XP with Service Pack 2 (or a later service pack).")%>
								            <%elseif bIE6onWin2003 then%>
									            <%=GetString(119, "You are accessing this site from an endpoint running Windows 2003 with Service Pack 1 (or a later service pack).")%>
								            <%elseif bIEonWin7 then%>
									            <%=GetString(129, "You are accessing this site from an endpoint running Windows Server 2008 R2.")%>
								            <%else%>
									            <%=GetString(120, "You are accessing this site from an endpoint running Windows Vista or Windows Server 2008.")%>
								            <%end if%>
								            <%if bWin64 = true then '64-bit browser%>
								                <li><b><%=GetString(125, "Forefront UAG endpoint components were not installed because you accessed this site using a 64-bit version of Internet Explorer. To install the components access the site using a 32-bit browser.")%></b></li>
								            <%end if%>
								            <%if EvaluateSessionParam(Components_ProblematicXPSP2) = true then 'will be false if it's not XP SP2%>
									            <li><b><%=GetString(115, "To ensure full site functionality a Windows update is required. To download and install the update click")%>&nbsp;<a href="<%=MSHotfixURL%>" target="_blank"><%=GetString(116, "here.")%></a><%=GetString(117, "You will be directed to another site for the download.")%></b></li>
								            <%end if%>
								            <%if bShowPopupMsg = true then%>
								                <li><%=GetString(118, "Internet Explorer is configured by default to block pop-ups. To receive inactivity timeout notifications and other warnings, configure the browser to allow pop-ups from this site.")%></li>
								            <%end if%>
								            </td>
							            </tr>
							            <!-- Windows XP Service Pack 2 / 2003 / Vista Message - End -->
							            <%end if%>
							            <tr>
								            <td class="notification">
							                <%=GetString(4, "This site is intended for authorized users only.")%><br/>
					                        <%=GetString(5, "If you experience access problems contact the <a href='mailto:'>site administrator</a>.")%>
				                            </td>
				                        </tr>
						            </table>
						        </td>
						    </tr>
						    <%end if 'isPDA=false%>
						</TABLE>
					</td>
					<td valign="top" class="contentright"></td>
				</tr>

				<!--#include virtual="InternalSite/inc/bottomText.inc"-->
			</TABLE>
		</td>
	</tr>
</TABLE>
</BODY>
<%
'portal was opened from an "opener" window
if g_login_type = RESOURCE_OPERATION_LOGIN and viewPopupMessage = true and isPDA = false then
%>
<script>
if (window.opener && !window.opener.closed)
{
	document.getElementById("openerExistsTD").style.display = "";
}
</script>
<%end if%>

</HTML>